import subprocess
import sys
import datetime

def run_command(command, step_name, exit_on_fail=True):
    
    print(f"Start step : {step_name}")
   
    
    try:
        process = subprocess.Popen(
            command, 
            shell=True, 
            stdout=sys.stdout, 
            stderr=sys.stderr
        )
        process.communicate()
        
        if process.returncode != 0:
            if exit_on_fail:
                print(f"\n Error : Step '{step_name}' has failed.")
                sys.exit(process.returncode)
            else:
                return False 
        else:
            print(f"\n Success: Step '{step_name}' completed successfully.")
            return True
            
    except Exception as e:
        print(f"\n Critical error in step '{step_name}': {str(e)}")
        sys.exit(1)

def main():
    print("Starting MLOps pipeline...")
    
    # 1. CT 
    train_cmd = "python submit_job.py"
    run_command(train_cmd, "CT stage")
    
    # 2. CD 
    eval_cmd = 'python src/evaluate_and_register.py'
    
    is_new_champion = run_command(eval_cmd, "Champion vs Challenger", exit_on_fail=False)
    
    # 3. Automatic PR
    if is_new_champion:
        print("\n New champion registered. Initiating automatic PR process...")
        
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        branch_name = f"auto-pr/new-champion-{timestamp}"
        
        commands = [
            f"git checkout -b {branch_name}",
            "git add .",
            'git commit -m "Auto-commit: New champion architecture / parameters"',
            f"git push -u origin {branch_name}",
            f'gh pr create --title "🚀 New Champion Model InceptionTime ({timestamp})" --body "Automated Pull Request generated by the local MLOps pipeline. The model has beaten the current champion." --base main'
        ]
        
        for cmd in commands:
            subprocess.run(cmd, shell=True)
            
        print(f"\n Pull requests have been made, Check your repository on GitHub.")
        
        
        subprocess.run("git checkout -", shell=True)
        
    else:
        print("\nModel did not beat the champion. No changes made.")

if __name__ == "__main__":
    main()